code --install-extension aaron-bond.better-comments
code --install-extension akamud.vscode-theme-onedark
code --install-extension Arvischain.arvischain-theme
code --install-extension BeardedBear.beardedtheme
code --install-extension beastdestroyer.firefox-quantum-themes
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension creasty.vscode-candle-theme
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension dustinsanders.an-old-hope-theme-vscode
code --install-extension Endormi.2077-theme
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.github-vscode-theme
code --install-extension GulajavaMinistudio.mayukaithemevsc
code --install-extension hasanakg.firebase-snippets
code --install-extension hediet.vscode-drawio
code --install-extension Heron.firefox-devtools-theme
code --install-extension hollowtree.vue-snippets
code --install-extension icrawl.discord-vscode
code --install-extension Janne252.fontawesome-autocomplete
code --install-extension jcbuisson.vue
code --install-extension jdinhlife.gruvbox
code --install-extension jolaleye.horizon-theme-vscode
code --install-extension jprestidge.theme-material-theme
code --install-extension kube.theme-kay
code --install-extension kuscamara.electron
code --install-extension lucasmsa.arkham-theme
code --install-extension Luxcium.pop-n-lock-theme-vscode
code --install-extension mariorodeghiero.vue-theme
code --install-extension Mikael.Angular-BeastCode
code --install-extension moyu.snapcode
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.Theme-MaterialKit
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension ngryman.codesandbox-theme
code --install-extension Nimda.deepdark-material
code --install-extension octref.vetur
code --install-extension PKief.material-icon-theme
code --install-extension pnp.polacode
code --install-extension ritwickdey.LiveServer
code --install-extension sdras.vue-vscode-snippets
code --install-extension seansassenrath.vscode-theme-superonedark
code --install-extension skyran.js-jsx-snippets
code --install-extension sldobri.bunker
code --install-extension taniarascia.new-moon-vscode
code --install-extension tinaciousdesign.theme-tinaciousdesign
code --install-extension tinkertrain.theme-panda
code --install-extension tobiasalthoff.atom-material-theme
code --install-extension uloco.theme-bluloco-dark
code --install-extension yummygum.city-lights-theme
